
name: Build OpenSSL Win32

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'OpenSSL tag'
        required: true
        default: 'openssl-3.5.1'

jobs:
  build-win32:
    runs-on: windows-latest

    steps:
      #- name: Debug list VS2022 install dirs (bare format)
      #  shell: cmd
      #  run: |
      #    dir "C:\Program Files\Microsoft Visual Studio\2022" /s /b
      - name: Checkout official OpenSSL
        uses: actions/checkout@v4
        with:
          repository: 'openssl/openssl'
          fetch-depth: 0
          path: 'openssl-src'

      - name: Checkout tag
        run: |
          cd openssl-src
          git checkout ${{ github.event.inputs.tag }}

      - name: Install prerequisites
        shell: pwsh
        run: choco install strawberryperl nasm -y
        
      - name: Add choco bin to PATH
        shell: cmd
        run: echo "C:\Program Files\NASM" >> %GITHUB_PATH%
      
      #- name: Debug Find nasm via CMD
      #  shell: cmd
      #  run: |
      #    echo Searching for nasm.exe on C: drive...
      #    where /R C:\ nasm.exe || echo "nasm not found"

      - name: Setup environment and compile test install
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x86
          #set PATH=C:\ProgramData\chocolatey\bin;%PATH%
          cd openssl-src
          perl Configure VC-WIN32 --prefix=%CD%\openssl-install
          nmake
          nmake test
          nmake install

      - name: Upload compiled libraries
        uses: actions/upload-artifact@v4
        with:
          name: openssl-win32
          path: openssl-src/openssl-install

