name: test_vcpkg

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'test'
        required: false
        default: 'demo'

jobs:
  build-win32:
    runs-on: windows-latest
    steps:
      - name: Install vcpkg
        shell: cmd
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          .\vcpkg\bootstrap-vcpkg.bat
      
      - name: Run vcpkg install for libwebsockets
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x86
          .\vcpkg\vcpkg.exe install libwebsockets:x86-windows
